# Generated by Django 4.2.8 on 2024-02-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_connection"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(fields=("follower", "following"), name="unique_connection"),
        ),
    ]
